server:
  port: 8002

spring:
  application:
    name: com.zy.communication
ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 300000

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #使用ip注册 客户端用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
